version: "3"
services:
  atcoder_python:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: atcoder_python-image
    container_name: atcoder_python-container
    tty: true
